config/routes.rb
Rails.application.routes.draw do

  resources :wikis do
    member  do
      get :collaborators
      put :add_collaborators
      put :remove_collaborators
    end
  end

  resources :charges, only: [:new, :create]

  devise_for :users

  resources :users, only: [:show]

  post 'users/unsubscribe'

  get 'about' => 'welcome#about'

  root 'welcome#index'

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  after_initialize { self.role ||= :standard }

  has_many :wikis
  has_many :collaborations
  has_many :wiki_collaborations, through: :collaborations, source: :wiki

  default_scope { order('created_at DESC') }

         before_save { self.email = email.downcase }

        #  validates :password, presence: true, length: { minimum: 6 }, if: "password.nil?"
        #  validates :password, length: { minimum: 6 }, allow_blank: true

         EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

         validates :email,
            presence: true,
            length: { minimum: 8, maximum: 100 },
            format: { with: EMAIL_REGEX }

  enum role: [:standard, :premium, :admin]

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborations
  has_many :collaborators, through: :collaborations, source: :user

  validates :title, presence: true, length: {minimum: 4}
  validates :body, presence: true
  validates :user, presence: true

  scope :visible_to, -> (user) { user ? all : where(private: false) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
  #before_action :authenticate_user!
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
before_action :authenticate_user!

  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      #Ask Jon about Amount class -> Amount.default
      amount: default_amount,
      description: "BigMoney Membership - #{current_user.name}",
      currency: 'usd'
    )
# byebug
    current_user.role = "premium"
    if current_user.save
      flash[:notice] = "Thanks for all the money, #{current_user.email}! your account has been upgraded to Premium"
    else
      flash[:notice] = "Error taking your money, #{current_user.email}! your account has been upgraded to Premium"
    end
    redirect_to wikis_path # or wherever
    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

  def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "BigMoney Membership - #{current_user.name}",
     amount: default_amount
   }
  end

  private

  def default_amount
    10_00
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @allusers = User.all
    authorize @user
    respond_to do |format|
        format.html # show.html.erb
        format.xml { render :xml => @user }
    end

    def unsubscribe
      @user = User.find(params[:id])
      @user.role = "standard"
      if @user.save
        flash[:notice] = "You have successfully changed the role of your user to Standard "
      else
        flash[:notice] = "There was an error changing the role of your user"
      end
      redirect_to wikis_path
    end

    def premium
      @user = User.find(params[:id])
      @user.role = "premium"
      if @user.save
        flash[:notice] = "You have successfully changed the role of your user to Standard "
      else
        flash[:notice] = "There was an error changing the role of your user"
      end
      redirect_to wikis_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

before_action :authenticate_user!, except: [:index, :show]

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
      @wiki = Wiki.find(params[:id])
      authorize @wiki
  end

  def update
      @wiki = Wiki.find(params[:id])
      #@wiki.assign_attributes(wiki_params)
      authorize @wiki
      if @wiki.update(wiki_params)
        flash[:notice] = "Wiki was saved."
        redirect_to @wiki
      else
        flash.now[:alert] = "There was an error saving the wiki. Please try again."
        render :edit
      end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.delete
      flash[:notice] =  "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :show
    end
  end

  def collaborators
    @wiki = Wiki.find(params[:id])
    @allusers = User.all
    # params[user_ids][].each |id|
        # add the ones checked
    #   Collaboration.create user_id: id, wiki_id: @wiki.id
        # remove the ones not checked
     #end
  end

  def add_collaborators
    @wiki = Wiki.find(params[:id])
    @user = User.find(params[:user_id])
    if Collaboration.create user_id: @user.id, wiki_id: @wiki.id
      flash[:notice] =  "\"#{@user.name}\" was added successfully."
      redirect_to @wiki
    else
      flash[:notice] =  "there was a problem adding \"#{@user.name}\" as a collaborator"
      redirect_to @wiki
    end
  end

  def remove_collaborators
    @wiki = Wiki.find(params[:id])
    @user = User.find(params[:user_id])
    @collaborator = Collaboration.where(user_id: @user , wiki_id: @wiki.id).first
    if @collaborator.destroy
      flash[:notice] =  "\"#{@user.name}\" was removed successfully."
      redirect_to @wiki
    else
      flash[:notice] =  "there was a problem removing \"#{@user.name}\" as a collaborator"
      redirect_to @wiki
    end
  end

  def collaborators?
    @wiki = Wiki.find(params[:id])
    @user = User.find(params[:user_id])

  end

  private

    def wiki_params
      params.require(:wiki).permit(:title, :body, :private)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
      options = {
        filter_html:     true,
        hard_wrap:       true,
        link_attributes: { rel: 'nofollow', target: "_blank" },
        space_after_headers: true,
        fenced_code_blocks: true
      }

      extensions = {
        autolink:           true,
        superscript:        true,
        disable_indented_code_blocks: true
      }

      renderer = Redcarpet::Render::HTML.new(options)
      @markdown ||= Redcarpet::Markdown.new(renderer, extensions)

      @markdown.render(text).html_safe
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
   <h4>Click the button!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <ul class="nav nav-tabs">
      <li><%=link_to "Welcome", root_path%></li>
      <li><%=link_to "About", about_path%></li>
      <li><%=link_to "Wikis", wikis_path%></li>
        <% if user_signed_in? %>
    </ul>
        <ul class ="nav nav-tabs navbar-right">
          <li style="padding: 14px"> Signed in as: <strong><%= current_user.email %></strong> </li>
          <li> <%= link_to 'Edit profile', user_path(current_user), :class => 'navbar-link' %> </li>
          <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
        </ul>
        <% else %>
       <li> <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> </li>
       <li> <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %> </li>
        </ul>
     <% end %>
</div>

    <% if flash[:notice] %>
       <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
     <% elsif flash.now[:alert] %>
       <div class="alert alert-danger">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash.now[:alert] %>
       </div>
     <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
     <% end %>

<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="media">
      <div class="media-title">
        <h1><%= @user.name %></h1>
      </div>

      <div class= "media-body">
        <h1 class="media-heading">Wikis created by me</h1>
        <% @user.wikis.each do |wiki|%>
        <h2><%=link_to(wiki.title, wiki)%></h2>
        <%end%>
        <h1 class="media-heading">Wikis where I am a collaborator<h1>
          <% @user.wiki_collaborations.each do |collaboration|%>
            <h2><%=link_to(collaboration.title, collaboration)%></h2>
          <%end%>

        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div>
        <%if policy(@user).premium_list?%>
        <%=button_to "Go back to Standard", users_unsubscribe_path, {method: 'post', :params => params, class: 'btn btn-success', type:'button', style:'display:inline-block',data: { confirm: "Are you sure?" }} %><br>
        <%end%>
      </div>
      <%=button_to "Edit User", edit_user_registration_path, {method: 'get', class: 'btn btn-success', type:'button', style:'display:inline-block'}%>
    </div>
  </div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div>
  <div class= "row">
    <div class= "col-md-12">
      <h1>Welcome to Blocipedia</h1>
    </div>
  </div>
  <% if !user_signed_in?%>
  <div class "row">
    <div class= "col-md-6">
      <div class="media-body">
           <h1 class="media-heading">
             <%=link_to "Sign In", new_user_session_path%>
           </h4>
      </div>
    </div>
    <div class= "col-md-6">
      <div class="media-body">
          <h1 class="media-heading">
        <%=link_to "Sign Up", new_user_registration_path %>
          </h1>
      </div>
    </div>
  </div>
  <%end%>
  <div class= "row">
    <div class= "col-md-6">
      <div class="media-body">
        <h1 class="media-heading">
          <%=link_to "See Wikis", wikis_path %>
        </h1>
        </div>
      </div>
      <div class= "col-md-6">
        <div class="media-body">
          <h1 class="media-heading">
            <%=link_to "Upgrade to create Private Posts", new_charge_path %>
          </h1>
          </div>
        </div>
  </div>


</div>

app/views/wikis/_form.html.erb
<div class="col-md-8">
  <%= form_for @wiki do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
    </div>
      <% if policy(:wiki).make_private? %>
        <div class="form-group">
          <%= f.label :private %>
          <%= f.check_box :private, class: 'checkbox' %>
        </div>
        <%end%>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/wikis/collaborators.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="media">
      <div class="media-title">
        <h1><%= @wiki.title %></h1>
      </div>

      <div class= "media-body">

        <h2>Add Collaborators to the <%=link_to(@wiki.title, @wiki)%> Wiki</h2>

        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Give Access</th>
            </tr>
          </thead>
          <tbody>
            <% @allusers.each do |user|%>
            <tr>
              <td><%=user.name%></td>
              <td><%=user.email%></td>
              <% if !Collaboration.where(user_id: user.id , wiki_id: @wiki.id).empty?%>
                <td><%=button_to "Remove Collaborator", remove_collaborators_wiki_path, {method: 'put', params: { user_id: user.id }, class: 'btn btn-success', type:'button', style:'display:inline-block',data: { confirm: "Are you sure?" }} %></td>
              <% else %>
                <td><%=button_to "Add Collaborator", add_collaborators_wiki_path, {method: 'put', params: { user_id: user.id }, class: 'btn btn-success', type:'button', style:'display:inline-block',data: { confirm: "Are you sure?" }} %></td>
              <% end %>
            </tr>
            <%end%>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for Wikis</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <%= render "wikis/form"%>
 </div>

app/views/wikis/index.html.erb
<h1>All Posts</h1>
<div class="row">
  <div class="col-md-8">
      <div class="media">
        <div class="media-body">
          <% @wikis.each do |wiki| %>
            <h4 class="media-heading">
              <%= link_to wiki.title, wiki %>
              <% end %>
            </h4>
        </div>
      </div>
    </div>

  <div class="col-md-4">
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-danger' %>
  </div>
</div>

app/views/wikis/new.html.erb
 <h1>New Wiki</h1>

  <div class="row">
    <div class="col-md-4">
      <p>Guidelines for Wikis</p>
      <ul>
        <li>Make sure it rhymes.</li>
        <li>Don't use the letter "A".</li>
        <li>The incessant use of hashtags will get you banned.</li>
      </ul>
    </div>
    <%= render "wikis/form"%>
  </div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

 <div class="row">
   <div class="col-md-8">
     <p><%= markdown(@wiki.body) %></p>
      <small>
        submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%=@wiki.user.name %>
        <h3> Collaborators</h3>
        <% @wiki.collaborators.each do |collaborator|%>
          <h5><%=collaborator.name%></h5>
        <%end%>
       </small>

   </div>
   <div class="col-md-4">
     <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
     <%if policy(@wiki).make_private?%>
        <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
        <%= link_to "Add Collaborators", collaborators_wiki_path(@wiki), class: 'btn btn-success' %>
     <%end%>
   </div>
 </div>